remote_theme: pages-themes/cayman
title: LIA+ AgriFood
description: Laboratório de Inteligência Artificial e Tecnologias Disruptivas em Sistemas Agroalimentares.
show_downloads: false
cayman_theme_background_image: /assets/banner.jpg
